name: LagAssist
authors: [Stefatorus, EntryRise, alvindimas05]
version: 2.31
api-version: 1.13
description: LagAssist is an advanced anti-lag solution that allows server owners find and remove lag using multiple advanced and efficient methods.
main: org.alvindimas05.lagassist.Main
softdepend: [Vault]
commands:
  lagassist:
    description: The main command of LagAssist, a Performance Analysis and Optimization Tool.
